server:
  port: 8082

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:sqlite:auth_service.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  expiration: 1800000
  refresh-expiration: 86400000

# ConfigVault Integration
config:
  vault:
    uri: http://localhost:8888
    username: admin
    password: changeme
    region: us-east-1

# Logging
logging:
  level:
    com.ecolightcline: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/auth-service.log
    max-size: 10MB
    max-history: 7

# Actuator - Enhanced monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, loggers, env, beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      percentiles:
        "[http.server.requests]": 0.5, 0.75, 0.95, 0.99
  tracing:
    sampling:
      probability: 1.0

# Service Discovery with Eureka
eureka:
  client:
    service-url:
      defaultZone: http://admin:eureka-password@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
